exporters:
  debug:
    verbosity: detailed

  otlphttp/otel-desktop-viewer:
    endpoint: http://otel-desktop-viewer:4318

  otlphttp/otel-tui:
    endpoint: http://otel-tui:4318
    sending_queue:
      enabled: true

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

connectors:
  spanmetrics:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, spanmetrics, otlphttp/otel-desktop-viewer, otlphttp/otel-tui]

    metrics:
      receivers: [otlp, spanmetrics]
      exporters: [debug, otlphttp/otel-tui]

    logs:
      receivers: [otlp]
      exporters: [debug, otlphttp/otel-tui]
